[[constraint]]
  name = "github.com/pulumi/pulumi"
  version = "v0.15.1"

[[constraint]]
  branch = "master"
  name = "github.com/pulumi/pulumi-terraform"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-alicloud"
  version = "v1.20.0"

[[override]]
  name = "github.com/aliyun/fc-go-sdk"
  revision = "2b25e8a561f05dd8adae9a37f462666ce58c71d9"

[[override]]
  name = "github.com/hashicorp/terraform"
  version = "v0.11.0"

[[override]]
  name = "github.com/jmespath/go-jmespath"
  version = "v0.2.2"

[[override]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "v16.2.1"
